server:
  port: 8021
spring:
  # 给项目来个名字
  application:
    name: rabbitmq-demo
  # 配置rabbitMq 服务器
  rabbitmq:
    host: 139.196.183.233
    port: 5672
    username: user
    password: password
    # 虚拟host 可以不设置, 使用server默认host
    virtual-host: /test
    
    #消息确认配置项
    #确认消息已发送到交换机(Exchange)
    publisher-confirms: true  # 如果因为版本问题, 无法回调, 需要改为 publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true